# Generated by Django 6.0.3 on 2026-04-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('pickup_time', models.DateTimeField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_time', models.DateTimeField()),
            ],
        ),
    ]
