# Generated by Django 6.0.3 on 2026-04-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_delete_tours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='assigned_by',
            new_name='created_by',
        ),
    ]
