# Generated by Django 6.0.3 on 2026-04-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_rename_assigned_by_tour_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='dropoff_time',
        ),
    ]
